apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-prod
  namespace: argocd2
spec:
  project: default
  source:
    repoURL: https://github.com/DmitriyKruchkov/argocd-prac.git
    targetRevision: main
    path: apps/myapp/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: false   # prod: ручной контроль, не откатывать ручные фиксы автоматом
    syncOptions:
      - CreateNamespace=true
